### PR TITLE
File Service Create Bucket

### PR DESCRIPTION
**Pull request by zinichakraborty**

### CODE REVIEW

**Review by tmthecoder — CHANGES_REQUESTED** [review]
Please update the .proto file and use the Controller annotation to link the proto service with your controller.

Additionally, add tests for the bucket creation (message me for the development credentials to an actual S3/B2 bucket)

**Review by tmthecoder — CHANGES_REQUESTED** [review]
@zinichakraborty Make sure to run `pnpm gen-proto` before a push, run `pnpm format:write` & `ppm lint` to make sure there aren't format/compile/lint errors

**Comment by zinichakraborty** [comment]
I can't seem to run it without docker and docker is failing currently

**Comment by tmthecoder** [comment]
None of those commands should need docker; they're run from your machine directly

**Review by tmthecoder — APPROVED** [review]
I made a lot of fixes, there was a lot missing in the wiring up with proto files & service integrations. Please take a look for future work on infra

**Pull request merged**
